name: Codemark Review

on:
  push:
    paths:
      - 'src/**'
  pull_request:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install Dependencies
        run: poetry install
      - name: Run Codemark (SARIF)
        run: poetry run codemark review src/ --format sarif > codemark.sarif
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: codemark.sarif
